
language: python
python:
  - "2.7"

dist: trusty
sudo: required

branches:
  only:

before_install: 
  - sudo apt-get install gfortran
  - sudo apt-get install libopenmpi-dev
  - sudo apt-get install openmpi-bin
  - sudo apt-get install imagemagick
  - pip install scipy
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install recommonmark
  - pip install matplotlib
  - pip install pytest-cov
  - pip install codecov
  - cd lib/hypre/src
  - ./configure
  - make install
  - cd ../../..

install: 
  - pip install -e .

script:
  - pytest --cov=aronnax -k 'not Hypre'
  - codecov
  - pytest --cov=aronnax -k 'Hypre'
  - codecov
